### ISSUE TITLE
GPU memory size

### ISSUE THREAD

**Issue by beef-broccoli** [psipred/DeepCov#3]
Hello,

I'm trying to run the training script that was given, and did not modify any code. I'm running it on GPU, and it throws this memory exception for the first training example:

```
Starting training...
Traceback (most recent call last):
  File "/home/jason/anaconda3/lib/python3.7/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
RuntimeError: GpuCorrMM failed to allocate working memory of 1600 x 246016


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lasagne_cov_train.py", line 249, in <module>
    main()
  File "lasagne_cov_train.py", line 176, in main
    train_err += train_func1(inputs, targets, wtmaps)
  File "/home/jason/anaconda3/lib/python3.7/site-packages/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/jason/anaconda3/lib/python3.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/jason/anaconda3/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/jason/anaconda3/lib/python3.7/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
RuntimeError: GpuCorrMM failed to allocate working memory of 1600 x 246016

Apply node that caused the error: GpuCorrMM{half, (1, 1), (1, 1), 1, False}(GpuContiguous.0, GpuContiguous.0)
Toposort index: 235
Inputs types: [GpuArrayType<None>(float32, (True, False, False, False)), GpuArrayType<None>(float32, 4D)]
Inputs shapes: [(1, 64, 496, 496), (64, 64, 5, 5)]
Inputs strides: [(62980096, 984064, 1984, 4), (6400, 100, 20, 4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[GpuCAReduceCuda{add}{0, 2, 3}(GpuCorrMM{half, (1, 1), (1, 1), 1, False}.0), GpuElemwise{sub,no_inplace}(GpuCorrMM{half, (1, 1), (1, 1), 1, False}.0, GpuElemwise{Composite{(((i0 / i1) / i2) / i3)}}[]<gpuarray>.0), GpuElemwise{sub,no_inplace}(GpuCorrMM{half, (1, 1), (1, 1), 1, False}.0, InplaceGpuDimShuffle{x,0,x,x}.0)]]
```

I'm just wondering what's the GPU memory you guys ran this on? or is there any way to resolve this? I'm running this on a 8GB GeForce RTX 2070 Max-Q and a 32GB RAM, which is pretty decent but clearly cant handle the size of this matrix...

**Comment by shaunmk** [comment]
We trained the models on a Titan Xp with 12G of GPU memory.

**Comment by shaunmk** [comment]
You could try changing out `nndef.py` for one of the smaller models. The models with various receptive field sizes are in the subdirectories of `covar-model-all`.

**Comment by shaunmk** [comment]
I'm going to close this issue for now; If there are still problems feel free to reopen it.

**Comment by beef-broccoli** [comment]
This should be a theano issue; when the same function is called with different input shapes (which in this case is different sequence length), the GPU backend keeps allocating memory and eventually it blows up.
 
See: [https://github.com/Theano/Theano/issues/5382](url)

preallocating memory with `THEANO_FLAGS='gpuarray.preallocate=x` seems to help.
